### ISSUE TITLE
READMEの修正

### ISSUE THREAD

**Issue by sekken-11** [sekken-11/GachaDiary#83]
ER図を変更して実装したため、問題がないか確認していただきたいです。

#### 変更前
![](https://gyazo.com/6d27d6eb11f0c4714c2e3f343a2dd737.png)
#### 変更後
![](https://gyazo.com/589fdd74cb93c0c20525e8f61e23e303.png)
#### 変更理由・内容
変更前の形ですと、機能上`gachas`から`games`のデータを引き出すような機械が頻発するため、コードがかなり煩雑かつ冗長になることが想定されたからです。

また、下記のご指摘を実装前のER図提出時に受け、変更前の形にしたのですが、`ゲームの名前`も`石1つの値段`も常に作成者が変更できるような形にしているため、ユーザー間で共用にしてしまうと複雑な操作が必要になると思われました。

当該のプルリクエストでも書きましたが、当初、ゲーム名には表記揺れが存在し、そこまでデータ数を減らせないと考えていたことも理由の一つです。

>こちら、石を購入する個数が変わるたびにレコードが増えていく という認識で合っていますでしょうか？
上記の場合ですと、nameカラム等、値が重複するレコードがいくつも作られてしまうと思うので、
>- 石１つの値段
>- ゲームの名前
>- 上記のデータは別テーブルで管理し、そちらの値を外部キーで紐づけた方が良さそうな- 印象を受けました。

こちらがその際のプルリクエストです。
[https://github.com/sekken-11/g_exam/pull/5](https://github.com/sekken-11/g_exam/pull/5)

MVPの期限が近く、問題なければMVPレビュー依頼をさせていただこうと思っています。
よろしくお願いします。

**Comment by Tsuchiya2** [comment]
ER図は開発を進めていく中で変更があったら、適宜ご自身で書き換えていただいて大丈夫です。

**Comment by sekken-11** [comment]
対応ありがとうございます。
かしこまりました。
